hostname spine2

interface Loopback0
   ip address 10.255.0.2/32

interface Ethernet1
   description leaf1
   ip address 10.0.0.3/31
   ip ospf area 0

interface Ethernet2
   description leaf2
   ip address 10.0.0.7/31
   ip ospf area 0

router ospf 1
   router-id 10.255.0.2
   passive-interface Loopback0
   network 10.255.0.2/32 area 0
   network 10.0.0.2/31 area 0
   network 10.0.0.6/31 area 0

router bgp 65000
   router-id 10.255.0.2
   neighbor 10.255.1.1 remote-as 65101
   neighbor 10.255.1.1 update-source Loopback0
   neighbor 10.255.1.1 ebgp-multihop 3

   neighbor 10.255.1.2 remote-as 65102
   neighbor 10.255.1.2 update-source Loopback0
   neighbor 10.255.1.2 ebgp-multihop 3

   address-family ipv4
      neighbor 10.255.1.1 activate
      neighbor 10.255.1.2 activate